### PR TITLE
Add relevant aspects of the UBC Office of Research Ethics document on Using Online Surveys

### PR DESCRIPTION
**Pull request by mchiriboga**

### CODE REVIEW

**Comment by xiaoweideng** [comment]
Hi @mchiriboga, you haven't pulled from origin branch yet. Could you merge and then modify?

**Comment by mchiriboga** [comment]
Hi @xiaoweideng , 
As mentioned on slack, I'm trying to solve the conflicts first, my PR is not concluded yet.
I'll ping when it's ready.

**Comment by mchiriboga** [comment]
@xiaoweideng it's ready now 😉

**Comment by xiaoweideng** [comment]
Thank you!

**Pull request merged**
